# Generated by Django 4.2.4 on 2024-10-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardsLists',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lists_order', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'cards_lists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WordCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('word', models.CharField(max_length=30)),
                ('word_level', models.CharField(max_length=5)),
                ('word_language', models.CharField(max_length=30)),
                ('word_class', models.CharField(max_length=30)),
                ('word_description', models.TextField(blank=True, null=True)),
                ('word_translation', models.CharField(max_length=255)),
                ('word_example', models.TextField(blank=True, null=True)),
                ('word_synonyms', models.CharField(blank=True, max_length=255, null=True)),
                ('word_image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'word_cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WordLists',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('submition_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('creator', models.IntegerField(blank=True, null=True)),
                ('moderator', models.IntegerField(blank=True, null=True)),
                ('learn_until_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'word_lists',
                'managed': False,
            },
        ),
    ]
